version: 1.0
os: linux
files:
  - source: /redis/about.php
    destination: /var/www/html/wp-admin/about.php
hooks:
  BeforeInstall:
    - location: scripts/get_files_from_docker.sh
      timeout: 10
      runas: root
  
  AfterInstall:
    - location: scripts/restart_docker.sh
      runas: root