version: 0.1
os: linux
files:
  - source: /nginx-jenkins-docker-compose.yml
    destination: /home/ec2-user/test-jenkins
  - source: /wordpress-new
    destination: /home/ec2-user/test-jenkins
files_exists_behavior: OVERWRITE
hooks:
  # ApplicationStop:
  #   - location: scripts/stop_docker.sh
  #     timeout: 30
  #     runas: ec2-user
  BeforeInstall:
    - location: scripts/get_files_from_docker.sh
      timeout: 30
      runas: ec2-user
  AfterInstall:
    - location: scripts/restart_docker.sh
      timeout: 50
      runas: ec2-user