# Create a strong password here
requirepass "antsomi"

# AUTH password of the primary instance in case this instance becomes a replica
masterauth "antsomi"

# Enable AOF file persistence
appendonly yes

# Choose a name for the AOF file
appendfilename "master.aof"


#enable debug command
enable-debug-command yes